# go-standard flake (github.com/LarsArtmann/go-nix-helpers):
# packages.default, apps.default/test/lint/fmt, devShells.default/ci,
# checks.format/build/lint, treefmt (gofumpt + goimports + nixfmt),
# overlays.default — all generated by the module.
{
  description = "samber-linter: static analyzer that finds health-washing in samber/do v2 containers";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };

    go-nix-helpers = {
      url = "github:LarsArtmann/go-nix-helpers/master";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      imports = [ inputs.go-nix-helpers.flakeModules.go-standard ];

      go-standard = {
        pname = "samber-linter";
        # Refreshed 2026-10-02 (got-hash from the clean-HEAD FOD): the
        # cmdguard/cobra/fang CLI migration added module deps, invalidating
        # the pre-migration hash.
        vendorHash = "sha256-lp4uWTm6wyxC5MYfe5KGwzfSX7Ebh8pz4doQV2aqO6A=";
        description = "Static analyzer that detects health-washing in samber/do v2 dependency-injection containers";
        subPackages = [ "./cmd/samber-linter" ];

        # go-finding declares GOEXPERIMENT=jsonv2 as an ecosystem invariant
        # (documented loudly while required). No compiled file imports
        # encoding/json/v2 today; the test suite below verifies it stays
        # compatible.
        extraBuildAttrs = {
          env = {
            GOEXPERIMENT = "jsonv2";
            CGO_ENABLED = "0";
          };
          # Honest version in nix-built binaries: the binary would otherwise
          # report the bare fallback ("devel") because store builds carry no
          # VCS metadata. dirtyShortRev wins when the tree is dirty, matching
          # the resolveVersion source-build convention (devel+<rev>[.dirty]).
          ldflags = [
            "-X main.version=devel+${inputs.self.dirtyShortRev or inputs.self.shortRev or "unknown"}"
          ];
          # buildGoModule's default checkPhase tests only the built
          # subPackages (cmd/samber-linter has no test files). Test the whole
          # module so the golden corpus actually gates every nix build.
          checkPhase = ''
            runHook preCheck
            go test -count=1 ./...
            runHook postCheck
          '';
        };
        shellExtraEnv = {
          GOEXPERIMENT = "jsonv2";
        };

        # Hermetic golangci-lint under `nix flake check`, matching CI.
        lintAsCheck = true;
      };

      # Module default (`go test -race`) needs a C compiler and no
      # GOEXPERIMENT; run the CI-equivalent suite instead.
      perSystem =
        {
          pkgs,
          lib,
          ...
        }:
        let
          # dprint owns markdown/json/yaml/dockerfile (treefmt owns go/nix
          # only), so hand-edited markdown is gated by this check instead of
          # silently passing `nix flake check`. The repo's dprint.json pins
          # plugin URLs fetched over the network; pinning the same files by
          # hash and injecting them as store paths keeps the check hermetic.
          dprintPluginHashes = {
            "https://plugins.dprint.dev/json-0.23.0.wasm" =
              "sha256-Ph8bfBQn32vYmBoRqqLEZv3o0RFend5MZSEwRYU5RDw=";
            "https://plugins.dprint.dev/g-plane/pretty_yaml-v0.6.0.wasm" =
              "sha256-QKL92nBAMX6xsjUg86AHaaVXHu2wScTKkXXBue66Aa4=";
            "https://plugins.dprint.dev/markdown-0.22.1.wasm" =
              "sha256-SQb7sDiXdzKq4OIW5LC5V+JyL415KCZgzLNtJ90FHxc=";
            "https://plugins.dprint.dev/dockerfile-0.4.1.wasm" =
              "sha256-3JU2sddEiX0TrT0GIfVR+PNiFD+fbQb/B4Hg4El8t5Q=";
          };
          dprintPlugins = lib.mapAttrsToList (
            url: hash: pkgs.fetchurl { inherit url hash; }
          ) dprintPluginHashes;
        in
        {
          apps.test = {
            type = "app";
            program = lib.mkForce (
              lib.getExe (
                pkgs.writeShellApplication {
                  name = "run-test";
                  runtimeInputs = [ pkgs.go_1_27 ];
                  text = ''
                    GOEXPERIMENT=jsonv2 CGO_ENABLED=0 go test -count=1 ./...
                  '';
                }
              )
            );
          };

          checks.format-dprint =
            pkgs.runCommand "samber-linter-dprint-check"
              {
                nativeBuildInputs = [
                  pkgs.dprint
                  pkgs.jq
                ];
                pluginPaths = lib.concatStringsSep " " dprintPlugins;
              }
              ''
                # Fail loudly when dprint.json references a version the flake does
                # not pin: the rewrite below would silently run stale plugins.
                for u in $(jq -r '.plugins[]' ${inputs.self}/dprint.json); do
                  base=$(basename "$u")
                  found=0
                  for p in $pluginPaths; do
                    case $(basename "$p") in
                      *"$base") found=1 ;;
                    esac
                  done
                  if [ "$found" = 0 ]; then
                    echo "dprint plugin drift: dprint.json references '$u' but flake.nix pins only: $pluginPaths"
                    exit 1
                  fi
                done

                jq '.plugins = $ARGS.positional' ${inputs.self}/dprint.json --args $pluginPaths > config.json
                export HOME=$TMPDIR
                cd ${inputs.self}
                dprint check --config "$TMPDIR/config.json"
                touch $out
              '';

          # One golangci-lint version everywhere (AGENTS policy): the CI action
          # pin, the custom-build pin, and the nixpkgs package the hermetic
          # lint check runs must agree. A golangci binary built with a go
          # older than the go.mod floor refuses the whole config, so drift
          # here means "green locally proves nothing about CI lint" (the
          # 2026-10-02 alert) — fail loudly instead.
          checks.golangci-version-drift =
            pkgs.runCommand "samber-linter-golangci-pin-drift" { nixpkgsVersion = pkgs.golangci-lint.version; }
              ''
                fail() {
                  echo "golangci-lint version drift: $1"
                  echo "Policy: one version everywhere. Move the CI lint pin (.github/workflows/ci.yml), .custom-gcl.yml, and nixpkgs together, then re-run 'nix run .#lint' before pushing."
                  exit 1
                }

                pin_gcl=$(sed -n 's/^version:[[:space:]]*\(v[0-9.]\+\)[[:space:]]*$/\1/p' ${inputs.self}/.custom-gcl.yml)
                [ -n "$pin_gcl" ] || fail "no 'version: vX.Y.Z' line found in .custom-gcl.yml"

                pin_ci=$(sed -n 's/^[[:space:]]*version:[[:space:]]*\(v[0-9.]\+\)[[:space:]]*$/\1/p' ${inputs.self}/.github/workflows/ci.yml)
                [ -n "$pin_ci" ] || fail "no golangci-lint 'version: vX.Y.Z' pin found in .github/workflows/ci.yml"

                [ "$pin_gcl" = "$pin_ci" ] || fail "CI pin $pin_ci != .custom-gcl.yml pin $pin_gcl"

                [ "v$nixpkgsVersion" = "$pin_gcl" ] || fail "nixpkgs golangci-lint $nixpkgsVersion != pin $pin_gcl (hermetic lint would verify a different binary than CI runs)"

                echo "golangci-lint pins aligned: $pin_gcl (nixpkgs $nixpkgsVersion)"
                touch $out
              '';
        };
    };
}
