# go-standard flake (github.com/LarsArtmann/go-nix-helpers):
# packages.default, apps.default/test/lint/fmt, devShells.default/ci,
# checks.format/build/lint, treefmt (gofumpt + goimports + nixfmt),
# overlays.default — all generated by the module.
{
  description = "samber-linter: static analyzer that finds health-washing in samber/do v2 containers";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };

    go-nix-helpers = {
      url = "git+ssh://git@github.com/LarsArtmann/go-nix-helpers?ref=master";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      imports = [ inputs.go-nix-helpers.flakeModules.go-standard ];

      go-standard = {
        pname = "samber-linter";
        vendorHash = "sha256-Ja/dDCwIcqTiYAWQnJL8MKR65fv+GD1gXFK9ptlfhbM=";
        description = "Static analyzer that detects health-washing in samber/do v2 dependency-injection containers";
        subPackages = [ "./cmd/samber-linter" ];

        # go-finding declares GOEXPERIMENT=jsonv2 as an ecosystem invariant
        # (documented loudly while required). No compiled file imports
        # encoding/json/v2 today; the test suite below verifies it stays
        # compatible.
        extraBuildAttrs = {
          env = {
            GOEXPERIMENT = "jsonv2";
            CGO_ENABLED = "0";
          };
          # buildGoModule's default checkPhase tests only the built
          # subPackages (cmd/samber-linter has no test files). Test the whole
          # module so the golden corpus actually gates every nix build.
          checkPhase = ''
            runHook preCheck
            go test -count=1 ./...
            runHook postCheck
          '';
        };
        shellExtraEnv = {
          GOEXPERIMENT = "jsonv2";
        };

        # Hermetic golangci-lint under `nix flake check`, matching CI.
        lintAsCheck = true;
      };

      # Module default (`go test -race`) needs a C compiler and no
      # GOEXPERIMENT; run the CI-equivalent suite instead.
      perSystem =
        { pkgs, lib, ... }:
        {
          apps.test = {
            type = "app";
            program = lib.mkForce (
              lib.getExe (
                pkgs.writeShellApplication {
                  name = "run-test";
                  runtimeInputs = [ pkgs.go_1_26 ];
                  text = ''
                    GOEXPERIMENT=jsonv2 CGO_ENABLED=0 go test -count=1 ./...
                  '';
                }
              )
            );
          };
        };
    };
}
