# go-standard flake (github.com/LarsArtmann/go-nix-helpers):
# packages.default, apps.default/test/lint/fmt, devShells.default/ci,
# checks.format/build/lint, treefmt (gofumpt + goimports + nixfmt),
# overlays.default — all generated by the module.
{
  description = "samber-linter: static analyzer that finds health-washing in samber/do v2 containers";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };

    go-nix-helpers = {
      url = "git+ssh://git@github.com/LarsArtmann/go-nix-helpers?ref=master";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      imports = [ inputs.go-nix-helpers.flakeModules.go-standard ];

      go-standard = {
        pname = "samber-linter";
        vendorHash = "sha256-2Oniqx8TjhQvwc9lN45lCystXdwJFE4U6Xp9rw/EzLo=";
        description = "Static analyzer that detects health-washing in samber/do v2 dependency-injection containers";
        subPackages = [ "./cmd/samber-linter" ];

        # go-finding declares GOEXPERIMENT=jsonv2 as an ecosystem invariant
        # (documented loudly while required). No compiled file imports
        # encoding/json/v2 today; the tests below verify it stays compatible.
        extraBuildAttrs.env = {
          GOEXPERIMENT = "jsonv2";
          CGO_ENABLED = "0";
        };
        shellExtraEnv = { GOEXPERIMENT = "jsonv2"; };

        # Hermetic golangci-lint under `nix flake check`, matching CI.
        lintAsCheck = true;
      };

      # Module default (`go test -race`) needs a C compiler and no
      # GOEXPERIMENT; run the CI-equivalent suite instead.
      perSystem =
        { pkgs, ... }:
        {
          apps.test = {
            type = "app";
            program = pkgs.lib.getExe (
              pkgs.writeShellApplication {
                name = "run-test";
                runtimeInputs = [ pkgs.go_1_26 ];
                text = ''
                  GOEXPERIMENT=jsonv2 CGO_ENABLED=0 go test -count=1 ./...
                '';
              }
            );
          };
        };
    };
}
